/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/posts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Posts */
        get: operations["list_posts_api_posts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/posts/{post_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Post */
        get: operations["get_post_api_posts__post_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/channels": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Channels */
        get: operations["list_channels_api_channels_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/channels/{channel_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Channel */
        get: operations["get_channel_api_channels__channel_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Chats */
        get: operations["list_chats_api_chats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chats/graph": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Chat Graph
         * @description Return chat tree with roots first; children nested via parent_chat_id.
         *
         *     Single SQL query; tree assembly is in-memory. Telethon enrichment is
         *     intentionally skipped for the tree endpoint — tile renders 1+ times
         *     per poll, member_count drilldown lives on /chats/:id.
         *
         *     Self-loops (parent_chat_id == id) and orphans (parent_chat_id points
         *     to a missing/deleted chat) become roots; multi-hop cycles aren't
         *     detected here — admins set parent_chat_id manually so cycles would
         *     be intentional misuse, not a runtime hazard.
         */
        get: operations["get_chat_graph_api_chats_graph_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chats/{chat_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Chat */
        get: operations["get_chat_api_chats__chat_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/costs/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Session Cost */
        get: operations["session_cost_api_costs_session_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/spam/pings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Pings
         * @description Most recent ad-detector hits, newest first.
         *
         *     With chat_id, filters to that chat. Joined against Chat to surface
         *     the title; chats not in the table (untracked groups) come back with
         *     chat_title = None.
         */
        get: operations["list_pings_api_spam_pings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stats/home": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Home Stats */
        get: operations["home_stats_api_stats_home_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agent/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get History */
        get: operations["get_history_api_agent_history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agent/clear": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Clear Conversation */
        post: operations["clear_conversation_api_agent_clear_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agent/turn": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Turn
         * @description SSE stream of one agent turn.
         *
         *     We open a fresh session_maker session inside the generator so the
         *     long-lived connection isn't tied to the request's get_session
         *     lifecycle (which closes when the route returns — generator continues
         *     afterwards).
         */
        post: operations["turn_api_agent_turn_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AgentHistory
         * @description Persisted-conversation snapshot for /agent.
         */
        AgentHistory: {
            /** User Id */
            user_id: number;
            /** Message Count */
            message_count: number;
            /** Messages */
            messages: components["schemas"]["AgentMessage"][];
        };
        /**
         * AgentMessage
         * @description One row in the chat-UI projection of the agent conversation.
         */
        AgentMessage: {
            /** Role */
            role: string;
            /** Text */
            text?: string | null;
            /** Tool Name */
            tool_name?: string | null;
            /** Tool Label */
            tool_label?: string | null;
            /** Result Preview */
            result_preview?: string | null;
        };
        /**
         * AgentTurnRequest
         * @description Body of POST /api/agent/turn.
         */
        AgentTurnRequest: {
            /** Message */
            message: string;
        };
        /**
         * ChannelDetail
         * @description Full channel payload — adds config + sources + recent posts summary.
         */
        ChannelDetail: {
            /** Id */
            id: number;
            /** Telegram Id */
            telegram_id: number;
            /** Username */
            username: string | null;
            /** Name */
            name: string;
            /** Description */
            description: string;
            /** Language */
            language: string;
            /** Enabled */
            enabled: boolean;
            /** Max Posts Per Day */
            max_posts_per_day: number;
            /** Critic Enabled */
            critic_enabled: boolean | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Review Chat Id */
            review_chat_id: number | null;
            /** Posting Schedule */
            posting_schedule: string[] | null;
            /** Publish Schedule */
            publish_schedule: string[] | null;
            /** Footer Template */
            footer_template: string | null;
            /** Discovery Query */
            discovery_query: string;
            /**
             * Modified At
             * Format: date-time
             */
            modified_at: string;
            /** Sources */
            sources: components["schemas"]["ChannelSourceRead"][];
            /** Recent Posts */
            recent_posts: components["schemas"]["PostRead"][];
        };
        /**
         * ChannelRead
         * @description List-page view of a channel — identifying + toggle fields only.
         */
        ChannelRead: {
            /** Id */
            id: number;
            /** Telegram Id */
            telegram_id: number;
            /** Username */
            username: string | null;
            /** Name */
            name: string;
            /** Description */
            description: string;
            /** Language */
            language: string;
            /** Enabled */
            enabled: boolean;
            /** Max Posts Per Day */
            max_posts_per_day: number;
            /** Critic Enabled */
            critic_enabled: boolean | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * ChannelSourceRead
         * @description RSS source attached to a channel.
         */
        ChannelSourceRead: {
            /** Id */
            id: number;
            /** Url */
            url: string;
            /** Source Type */
            source_type: string;
            /** Title */
            title: string | null;
            /** Language */
            language: string | null;
            /** Enabled */
            enabled: boolean;
            /** Relevance Score */
            relevance_score: number;
            /** Error Count */
            error_count: number;
            /** Last Fetched At */
            last_fetched_at: string | null;
            /** Last Error */
            last_error: string | null;
        };
        /**
         * ChatDetail
         * @description Full chat payload — adds heatmap grid + member-snapshot series + relationships.
         */
        ChatDetail: {
            /** Id */
            id: number;
            /** Title */
            title: string | null;
            /** Is Forum */
            is_forum: boolean;
            /** Is Welcome Enabled */
            is_welcome_enabled: boolean;
            /** Is Captcha Enabled */
            is_captcha_enabled: boolean;
            /** Parent Chat Id */
            parent_chat_id?: number | null;
            /** Relation Notes */
            relation_notes?: string | null;
            /** Member Count */
            member_count?: number | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Welcome Message */
            welcome_message: string | null;
            /** Time Delete */
            time_delete: number;
            /**
             * Modified At
             * Format: date-time
             */
            modified_at: string;
            /** Heatmap */
            heatmap: components["schemas"]["HeatmapCell"][];
            /** Member Snapshots */
            member_snapshots: components["schemas"]["MemberSnapshotPoint"][];
            /**
             * Children
             * @default []
             */
            children: components["schemas"]["ChatNode"][];
            /**
             * Spam Pings
             * @default []
             */
            spam_pings: components["schemas"]["SpamPingRead"][];
        };
        /**
         * ChatHeatmapSummary
         * @description Home tile: per-chat total activity over the last 7 days.
         *
         *     We send totals (not the full grid) to keep the home payload small;
         *     the full grid lives on /chats/:id.
         */
        ChatHeatmapSummary: {
            /** Chat Id */
            chat_id: number;
            /** Title */
            title: string | null;
            /** Total Messages */
            total_messages: number;
        };
        /**
         * ChatNode
         * @description Recursive node for the /chats/graph tree response.
         *
         *     member_count is intentionally NOT enriched here — the tree endpoint
         *     skips Telethon to avoid N+1 RPCs on every poll. Drill into /chats/:id
         *     for live counts.
         */
        ChatNode: {
            /** Id */
            id: number;
            /** Title */
            title: string | null;
            /** Relation Notes */
            relation_notes?: string | null;
            /**
             * Children
             * @default []
             */
            children: components["schemas"]["ChatNode"][];
        };
        /**
         * ChatRead
         * @description List-page view of a managed chat.
         */
        ChatRead: {
            /** Id */
            id: number;
            /** Title */
            title: string | null;
            /** Is Forum */
            is_forum: boolean;
            /** Is Welcome Enabled */
            is_welcome_enabled: boolean;
            /** Is Captcha Enabled */
            is_captcha_enabled: boolean;
            /** Parent Chat Id */
            parent_chat_id?: number | null;
            /** Relation Notes */
            relation_notes?: string | null;
            /** Member Count */
            member_count?: number | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * DraftBucket
         * @description Home tile: drafts grouped by channel.
         */
        DraftBucket: {
            /** Channel Id */
            channel_id: number;
            /** Channel Name */
            channel_name: string;
            /** Count */
            count: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HeatmapCell
         * @description One cell of the weekday×hour chat activity grid.
         *
         *     weekday: 0 = Monday, 6 = Sunday (matches datetime.weekday()).
         *     hour: 0..23, UTC.
         *     count: number of messages recorded in `messages` table for that cell
         *            over the lookback window.
         */
        HeatmapCell: {
            /** Weekday */
            weekday: number;
            /** Hour */
            hour: number;
            /** Count */
            count: number;
        };
        /**
         * HomeStats
         * @description Aggregated response backing the home dashboard's live tiles.
         *
         *     Keeps home to one round-trip; skeleton tiles are FE-only and don't
         *     appear here.
         */
        HomeStats: {
            /** Drafts */
            drafts: components["schemas"]["DraftBucket"][];
            /** Scheduled Next 24H */
            scheduled_next_24h: components["schemas"]["ScheduledPostEntry"][];
            session_cost: components["schemas"]["SessionCostSummary"];
            /**
             * Post Views
             * @default []
             */
            post_views: components["schemas"]["PostViewsEntry"][];
            /**
             * Chat Heatmap
             * @default []
             */
            chat_heatmap: components["schemas"]["ChatHeatmapSummary"][];
            /**
             * Members Delta
             * @default []
             */
            members_delta: components["schemas"]["MembersDeltaEntry"][];
            /**
             * @default {
             *       "count_24h": 0,
             *       "count_7d": 0,
             *       "recent": []
             *     }
             */
            spam_pings: components["schemas"]["SpamPingsSummary"];
        };
        /** MemberSnapshotPoint */
        MemberSnapshotPoint: {
            /**
             * Captured At
             * Format: date-time
             */
            captured_at: string;
            /** Member Count */
            member_count: number;
        };
        /**
         * MembersDeltaEntry
         * @description Home tile: members Δ over a window.
         *
         *     delta_24h / delta_7d: None when no baseline snapshot exists yet
         *     (first run, or snapshot history too short).
         */
        MembersDeltaEntry: {
            /** Chat Id */
            chat_id: number;
            /** Title */
            title: string | null;
            /** Current */
            current: number | null;
            /** Delta 24H */
            delta_24h: number | null;
            /** Delta 7D */
            delta_7d: number | null;
        };
        /**
         * OperationCostBucket
         * @description Per-operation slice of the session cost summary.
         *
         *     Operation is the pipeline phase (screening, generation, discovery,
         *     feedback, edit, source_discovery) — that's how cost_tracker groups
         *     usage internally.
         */
        OperationCostBucket: {
            /** Operation */
            operation: string;
            /** Tokens */
            tokens: number;
            /** Cost Usd */
            cost_usd: number;
            /** Calls */
            calls: number;
            /** Cache Savings Usd */
            cache_savings_usd: number;
        };
        /**
         * PostDetail
         * @description Full post payload for the detail page — adds source_items blob.
         */
        PostDetail: {
            /** Id */
            id: number;
            /** Channel Id */
            channel_id: number;
            /** Title */
            title: string;
            /** Post Text */
            post_text: string;
            /** Status */
            status: string;
            /** Image Url */
            image_url: string | null;
            /** Image Urls */
            image_urls: string[] | null;
            /** Source Url */
            source_url: string | null;
            /** Scheduled At */
            scheduled_at: string | null;
            /** Published At */
            published_at: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** External Id */
            external_id: string;
            /** Source Items */
            source_items?: {
                [key: string]: unknown;
            }[] | null;
        };
        /** PostRead */
        PostRead: {
            /** Id */
            id: number;
            /** Channel Id */
            channel_id: number;
            /** Title */
            title: string;
            /** Post Text */
            post_text: string;
            /** Status */
            status: string;
            /** Image Url */
            image_url: string | null;
            /** Image Urls */
            image_urls: string[] | null;
            /** Source Url */
            source_url: string | null;
            /** Scheduled At */
            scheduled_at: string | null;
            /** Published At */
            published_at: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * PostViewsEntry
         * @description Home tile: post view counts for the last N published posts.
         */
        PostViewsEntry: {
            /** Post Id */
            post_id: number;
            /** Channel Id */
            channel_id: number;
            /** Channel Name */
            channel_name: string;
            /** Title */
            title: string;
            /**
             * Published At
             * Format: date-time
             */
            published_at: string;
            /** Views */
            views: number;
        };
        /**
         * ScheduledPostEntry
         * @description Home tile: scheduled post appearing in the next 24h window.
         */
        ScheduledPostEntry: {
            /** Post Id */
            post_id: number;
            /** Channel Id */
            channel_id: number;
            /** Channel Name */
            channel_name: string;
            /** Title */
            title: string;
            /**
             * Scheduled At
             * Format: date-time
             */
            scheduled_at: string;
        };
        /**
         * SessionCostSummary
         * @description In-memory cost aggregation from app.channel.cost_tracker.
         *
         *     Resets whenever the bot restarts — this is a session view, not
         *     persistent history. Persistent storage is Phase 1.5 scope.
         */
        SessionCostSummary: {
            /** Total Tokens */
            total_tokens: number;
            /** Total Cost Usd */
            total_cost_usd: number;
            /** Total Calls */
            total_calls: number;
            /** Cache Read Tokens */
            cache_read_tokens: number;
            /** Cache Write Tokens */
            cache_write_tokens: number;
            /** Cache Savings Usd */
            cache_savings_usd: number;
            /** By Operation */
            by_operation: components["schemas"]["OperationCostBucket"][];
        };
        /**
         * SpamPingRead
         * @description One ad-detection event surfaced to the UI.
         */
        SpamPingRead: {
            /** Id */
            id: number;
            /** Chat Id */
            chat_id: number;
            /** Chat Title */
            chat_title?: string | null;
            /** User Id */
            user_id: number;
            /** Message Id */
            message_id: number;
            /** Kind */
            kind: string;
            /** Matches */
            matches: string[];
            /** Snippet */
            snippet: string | null;
            /**
             * Detected At
             * Format: date-time
             */
            detected_at: string;
        };
        /**
         * SpamPingsSummary
         * @description Home tile: rolling spam-ping counters + recent samples.
         */
        SpamPingsSummary: {
            /** Count 24H */
            count_24h: number;
            /** Count 7D */
            count_7d: number;
            /**
             * Recent
             * @default []
             */
            recent: components["schemas"]["SpamPingRead"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    list_posts_api_posts_get: {
        parameters: {
            query?: {
                /** @description Filter by PostStatus */
                status?: string | null;
                /** @description Filter by Channel.telegram_id */
                channel_id?: number | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PostRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_post_api_posts__post_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                post_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PostDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_channels_api_channels_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChannelRead"][];
                };
            };
        };
    };
    get_channel_api_channels__channel_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                channel_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChannelDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_chats_api_chats_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatRead"][];
                };
            };
        };
    };
    get_chat_graph_api_chats_graph_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatNode"][];
                };
            };
        };
    };
    get_chat_api_chats__chat_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                chat_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    session_cost_api_costs_session_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionCostSummary"];
                };
            };
        };
    };
    list_pings_api_spam_pings_get: {
        parameters: {
            query?: {
                /** @description Filter by chat_id */
                chat_id?: number | null;
                /** @description Max rows to return */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpamPingRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    home_stats_api_stats_home_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HomeStats"];
                };
            };
        };
    };
    get_history_api_agent_history_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentHistory"];
                };
            };
        };
    };
    clear_conversation_api_agent_clear_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    turn_api_agent_turn_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AgentTurnRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
