/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/magic-link": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Magic Link Login */
        post: operations["magic_link_login_api_auth_magic_link_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/public/catalog": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Public Catalog
         * @description Return only the fields that are safe to show without admin auth.
         */
        get: operations["get_public_catalog_api_public_catalog_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/public/join-check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Pass Join Check
         * @description Approve the caller's own pending join request.
         */
        post: operations["pass_join_check_api_public_join_check_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Chats */
        get: operations["list_chats_api_chats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chats/graph": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Chat Graph
         * @description Return chat tree with roots first; children nested via parent_chat_id.
         *
         *     Single SQL query; tree assembly is in-memory. Telethon enrichment is
         *     intentionally skipped for the tree endpoint — tile renders 1+ times
         *     per poll, member_count drilldown lives on /chats/:id.
         *
         *     Self-loops (parent_chat_id == id) and orphans (parent_chat_id points
         *     to a missing/deleted chat) become roots; multi-hop cycles aren't
         *     detected here — admins set parent_chat_id manually so cycles would
         *     be intentional misuse, not a runtime hazard.
         */
        get: operations["get_chat_graph_api_chats_graph_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chats/{chat_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Chat */
        get: operations["get_chat_api_chats__chat_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Chat */
        patch: operations["update_chat_api_chats__chat_id__patch"];
        trace?: never;
    };
    "/api/chats/{chat_id}/avatar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Chat Avatar
         * @description Stream the chat's avatar JPEG.
         *
         *     Reads the cached ``photo_file_id`` from the row, calls Bot API
         *     ``getFile`` to resolve the file_path, then proxies ``download_file``
         *     bytes back to the client. We proxy rather than 302-redirecting because
         *     the Telegram file URL contains the bot token; redirecting would leak it.
         *
         *     Browsers cache the response for 1h via Cache-Control. Cached bytes
         *     invalidate naturally when ``photo_file_id`` changes (the URL stays the
         *     same but the bytes don't — we accept the staleness window since the
         *     icon swap on rename is a low-impact event for an admin tool).
         */
        get: operations["get_chat_avatar_api_chats__chat_id__avatar_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chats/{chat_id}/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refresh Chat From Telegram
         * @description Synchronously pull latest title + photo from Telegram for one chat.
         *
         *     Manual counterpart to the hourly snapshot loop. Updates ``title`` (only
         *     if upstream gave us a non-empty string), ``photo_file_id``, and bumps
         *     ``last_synced_at`` to now. Member count is not refreshed here because
         *     it's served live by the TelethonStatsService cache (60–300s TTL) — a
         *     separate refresh would burn a Telethon RPC for marginal recency gain.
         *
         *     Telethon is optional; missing it just means we skip the title-sync leg
         *     and the response carries whatever title was already in the DB.
         */
        post: operations["refresh_chat_from_telegram_api_chats__chat_id__refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/spam/pings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Pings
         * @description Most recent ad-detector hits, newest first.
         *
         *     With chat_id, filters to that chat. Joined against Chat to surface
         *     the title; chats not in the table (untracked groups) come back with
         *     chat_title = None.
         */
        get: operations["list_pings_api_spam_pings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stats/home": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Home Stats */
        get: operations["home_stats_api_stats_home_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/{user_id}/block": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Block User */
        post: operations["block_user_api_users__user_id__block_post"];
        /** Unblock User */
        delete: operations["unblock_user_api_users__user_id__block_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get User Block Status */
        get: operations["get_user_block_status_api_users__user_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Sessions
         * @description List the calling admin's active sessions, current one flagged.
         */
        get: operations["list_sessions_api_admin_sessions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/sessions/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Revoke Session
         * @description Revoke one of the calling admin's sessions. Refuse to revoke the current one.
         */
        delete: operations["revoke_session_api_admin_sessions__session_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/system": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get System Status */
        get: operations["get_system_status_api_admin_system_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AdminSessionRead
         * @description Active admin session row — used by /settings to list logins.
         */
        AdminSessionRead: {
            /** Session Id */
            session_id: string;
            /** User Id */
            user_id: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Last Seen At
             * Format: date-time
             */
            last_seen_at: string;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            /** User Agent */
            user_agent: string | null;
            /** Ip */
            ip: string | null;
            /**
             * Is Current
             * @default false
             */
            is_current: boolean;
        };
        /** AuthMeResponse */
        AuthMeResponse: {
            /** User Id */
            user_id: number;
            /**
             * Auth Mode
             * @default telegram
             */
            auth_mode: string;
            /**
             * Is Authenticated
             * @default true
             */
            is_authenticated: boolean;
        };
        /**
         * ChatDetail
         * @description Full chat payload — adds heatmap grid + member-snapshot series + relationships.
         */
        ChatDetail: {
            /** Id */
            id: number;
            /** Title */
            title: string | null;
            /**
             * Resource Status
             * @enum {string}
             */
            resource_status: "discovered" | "approved" | "disabled";
            /** Is Forum */
            is_forum: boolean;
            /** Is Welcome Enabled */
            is_welcome_enabled: boolean;
            /** Is Captcha Enabled */
            is_captcha_enabled: boolean;
            /**
             * Is Service Cleanup Enabled
             * @default true
             */
            is_service_cleanup_enabled: boolean;
            /** Parent Chat Id */
            parent_chat_id?: number | null;
            /** Relation Notes */
            relation_notes?: string | null;
            /** Member Count */
            member_count?: number | null;
            /**
             * Has Photo
             * @default false
             */
            has_photo: boolean;
            /** Last Synced At */
            last_synced_at?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Welcome Message */
            welcome_message: string | null;
            /** Time Delete */
            time_delete: number;
            /**
             * Modified At
             * Format: date-time
             */
            modified_at: string;
            /** Heatmap */
            heatmap: components["schemas"]["HeatmapCell"][];
            /** Member Snapshots */
            member_snapshots: components["schemas"]["MemberSnapshotPoint"][];
            /**
             * Children
             * @default []
             */
            children: components["schemas"]["ChatNode"][];
            /**
             * Spam Pings
             * @default []
             */
            spam_pings: components["schemas"]["SpamPingRead"][];
            /**
             * Recent Senders
             * @default []
             */
            recent_senders: components["schemas"]["ChatSender"][];
        };
        /**
         * ChatHeatmapSummary
         * @description Home tile: per-chat total activity over the last 7 days.
         *
         *     We send totals (not the full grid) to keep the home payload small;
         *     the full grid lives on /chats/:id.
         */
        ChatHeatmapSummary: {
            /** Chat Id */
            chat_id: number;
            /** Title */
            title: string | null;
            /** Total Messages */
            total_messages: number;
        };
        /**
         * ChatNode
         * @description Recursive node for the /chats/graph tree response.
         *
         *     member_count is intentionally NOT enriched here — the tree endpoint
         *     skips Telethon to avoid N+1 RPCs on every poll. Drill into /chats/:id
         *     for live counts.
         */
        ChatNode: {
            /** Id */
            id: number;
            /** Title */
            title: string | null;
            /** Relation Notes */
            relation_notes?: string | null;
            /**
             * Has Photo
             * @default false
             */
            has_photo: boolean;
            /**
             * Children
             * @default []
             */
            children: components["schemas"]["ChatNode"][];
        };
        /**
         * ChatRead
         * @description List-page view of a managed chat.
         */
        ChatRead: {
            /** Id */
            id: number;
            /** Title */
            title: string | null;
            /**
             * Resource Status
             * @enum {string}
             */
            resource_status: "discovered" | "approved" | "disabled";
            /** Is Forum */
            is_forum: boolean;
            /** Is Welcome Enabled */
            is_welcome_enabled: boolean;
            /** Is Captcha Enabled */
            is_captcha_enabled: boolean;
            /**
             * Is Service Cleanup Enabled
             * @default true
             */
            is_service_cleanup_enabled: boolean;
            /** Parent Chat Id */
            parent_chat_id?: number | null;
            /** Relation Notes */
            relation_notes?: string | null;
            /** Member Count */
            member_count?: number | null;
            /**
             * Has Photo
             * @default false
             */
            has_photo: boolean;
            /** Last Synced At */
            last_synced_at?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * ChatSender
         * @description Recent sender in a chat — used for moderation actions.
         */
        ChatSender: {
            /** User Id */
            user_id: number;
            /** Username */
            username: string | null;
            /** First Name */
            first_name: string | null;
            /** Last Name */
            last_name: string | null;
            /** Message Count */
            message_count: number;
            /**
             * Last Seen
             * Format: date-time
             */
            last_seen: string;
            /** Blocked */
            blocked: boolean;
        };
        /**
         * ChatUpdate
         * @description Editable per-chat moderation settings. All fields optional — only the
         *     keys present in the body are applied (``exclude_unset``).
         */
        ChatUpdate: {
            /** Title */
            title?: string | null;
            /** Resource Status */
            resource_status?: ("discovered" | "approved" | "disabled") | null;
            /** Welcome Message */
            welcome_message?: string | null;
            /** Is Welcome Enabled */
            is_welcome_enabled?: boolean | null;
            /** Is Captcha Enabled */
            is_captcha_enabled?: boolean | null;
            /** Is Service Cleanup Enabled */
            is_service_cleanup_enabled?: boolean | null;
            /** Time Delete */
            time_delete?: number | null;
            /** Parent Chat Id */
            parent_chat_id?: number | null;
            /** Relation Notes */
            relation_notes?: string | null;
        };
        /**
         * FeatureFlagRead
         * @description One feature flag — surfaced as a badge in /settings.
         */
        FeatureFlagRead: {
            /** Name */
            name: string;
            /** Enabled */
            enabled: boolean;
            /**
             * Source
             * @default env
             */
            source: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HeatmapCell
         * @description One cell of the weekday×hour chat activity grid.
         *
         *     weekday: 0 = Monday, 6 = Sunday (matches datetime.weekday()).
         *     hour: 0..23, UTC.
         *     count: number of messages recorded in `messages` table for that cell
         *            over the lookback window.
         */
        HeatmapCell: {
            /** Weekday */
            weekday: number;
            /** Hour */
            hour: number;
            /** Count */
            count: number;
        };
        /**
         * HomeStats
         * @description Aggregated response backing the home dashboard's live tiles.
         *
         *     Keeps home to one round-trip; skeleton tiles are FE-only and don't
         *     appear here.
         */
        HomeStats: {
            /**
             * Chat Heatmap
             * @default []
             */
            chat_heatmap: components["schemas"]["ChatHeatmapSummary"][];
            /**
             * Members Delta
             * @default []
             */
            members_delta: components["schemas"]["MembersDeltaEntry"][];
            /**
             * @default {
             *       "count_24h": 0,
             *       "count_7d": 0,
             *       "recent": []
             *     }
             */
            spam_pings: components["schemas"]["SpamPingsSummary"];
        };
        /** JoinCheckRequest */
        JoinCheckRequest: {
            /**
             * Init Data
             * @description Raw Telegram.WebApp.initData string
             */
            init_data: string;
            /**
             * Query Id
             * @description Join request query id, carried in the Mini App URL
             */
            query_id: string;
        };
        /** JoinCheckResult */
        JoinCheckResult: {
            /** Status */
            status: string;
        };
        /** MagicLinkLoginPayload */
        MagicLinkLoginPayload: {
            /** Token */
            token: string;
        };
        /** MemberSnapshotPoint */
        MemberSnapshotPoint: {
            /**
             * Captured At
             * Format: date-time
             */
            captured_at: string;
            /** Member Count */
            member_count: number;
        };
        /**
         * MembersDeltaEntry
         * @description Home tile: members Δ over a window.
         *
         *     delta_24h / delta_7d: None when no baseline snapshot exists yet
         *     (first run, or snapshot history too short).
         */
        MembersDeltaEntry: {
            /** Chat Id */
            chat_id: number;
            /** Title */
            title: string | null;
            /** Current */
            current: number | null;
            /** Delta 24H */
            delta_24h: number | null;
            /** Delta 7D */
            delta_7d: number | null;
        };
        /**
         * PublicCatalogItem
         * @description Safe public projection for the chat catalog.
         */
        PublicCatalogItem: {
            /**
             * Resource Type
             * @constant
             */
            resource_type: "chat";
            /** Id */
            id: number;
            /** Title */
            title: string;
            /** Subtitle */
            subtitle?: string | null;
        };
        /**
         * SpamPingRead
         * @description One ad-detection event surfaced to the UI.
         */
        SpamPingRead: {
            /** Id */
            id: number;
            /** Chat Id */
            chat_id: number;
            /** Chat Title */
            chat_title?: string | null;
            /** User Id */
            user_id: number;
            /** Message Id */
            message_id: number;
            /** Kind */
            kind: string;
            /** Matches */
            matches: string[];
            /** Snippet */
            snippet: string | null;
            /**
             * Detected At
             * Format: date-time
             */
            detected_at: string;
        };
        /**
         * SpamPingsSummary
         * @description Home tile: rolling spam-ping counters + recent samples.
         */
        SpamPingsSummary: {
            /** Count 24H */
            count_24h: number;
            /** Count 7D */
            count_7d: number;
            /**
             * Recent
             * @default []
             */
            recent: components["schemas"]["SpamPingRead"][];
        };
        /**
         * SystemStatus
         * @description Read-only operational status for the /settings system card.
         */
        SystemStatus: {
            /** Super Admin Ids */
            super_admin_ids: number[];
            /** Telethon Connected */
            telethon_connected: boolean;
            /** Publish Bot Ready */
            publish_bot_ready: boolean;
            /** Allowed Origins */
            allowed_origins: string[];
            /** Session Ttl Days */
            session_ttl_days: number;
            /** Feature Flags */
            feature_flags: components["schemas"]["FeatureFlagRead"][];
        };
        /**
         * TelegramLoginPayload
         * @description Payload POSTed by the Telegram Login Widget. Extra keys are preserved so HMAC verifies.
         */
        TelegramLoginPayload: {
            /** Id */
            id: number;
            /** Auth Date */
            auth_date: number;
            /** Hash */
            hash: string;
        } & {
            [key: string]: unknown;
        };
        /**
         * UserBlockRequest
         * @description Body for POST /api/users/{id}/block. Set ``revoke_messages`` to also
         *     delete the user's recorded messages from all known chats.
         */
        UserBlockRequest: {
            /**
             * Revoke Messages
             * @default false
             */
            revoke_messages: boolean;
        };
        /** UserBlockResponse */
        UserBlockResponse: {
            /** User Id */
            user_id: number;
            /** Blocked */
            blocked: boolean;
            /** Message */
            message: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login_api_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TelegramLoginPayload"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthMeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    magic_link_login_api_auth_magic_link_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MagicLinkLoginPayload"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthMeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    me_api_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthMeResponse"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    get_public_catalog_api_public_catalog_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicCatalogItem"][];
                };
            };
        };
    };
    pass_join_check_api_public_join_check_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JoinCheckRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JoinCheckResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_chats_api_chats_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatRead"][];
                };
            };
        };
    };
    get_chat_graph_api_chats_graph_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatNode"][];
                };
            };
        };
    };
    get_chat_api_chats__chat_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                chat_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_chat_api_chats__chat_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                chat_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_chat_avatar_api_chats__chat_id__avatar_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                chat_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_chat_from_telegram_api_chats__chat_id__refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                chat_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_pings_api_spam_pings_get: {
        parameters: {
            query?: {
                /** @description Filter by chat_id */
                chat_id?: number | null;
                /** @description Max rows to return */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpamPingRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    home_stats_api_stats_home_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HomeStats"];
                };
            };
        };
    };
    block_user_api_users__user_id__block_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserBlockRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserBlockResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    unblock_user_api_users__user_id__block_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserBlockResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_user_block_status_api_users__user_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserBlockResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_sessions_api_admin_sessions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminSessionRead"][];
                };
            };
        };
    };
    revoke_session_api_admin_sessions__session_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_system_status_api_admin_system_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SystemStatus"];
                };
            };
        };
    };
}
