services:
  bot:
    build:
      context: .
      target: production
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    command: >
      sh -c "
      uv run alembic upgrade head &&
      uv run -m app.presentation.telegram
      "
