services:
  bot:
    image: ghcr.io/vsem-azamat/supervisor-telegram:latest
    container_name: moderator-bot
    env_file: .env
    environment:
      PYTHONUNBUFFERED: "1"
    volumes:
      - ./moderator_userbot.session:/app/moderator_userbot.session
      - bot-logs:/app/logs
    restart: unless-stopped

volumes:
  bot-logs:
