"""Initial schema.

Squashed from thirty-six migrations, twenty-two of which created and later
dropped tables for features that have left the repository. One of them also
created the pgvector extension, which forced the database image to carry it for
a column nothing reads any more.

This replaces them because the deployment starts from an empty volume. An
existing database cannot be brought forward onto this — it would need its data
moved across by hand.

Revision ID: fbeb70328d81
Revises:
Create Date: 2026-07-27
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "fbeb70328d81"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "admin_magic_links",
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.Column("used_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("token_hash"),
    )
    op.create_index(op.f("ix_admin_magic_links_expires_at"), "admin_magic_links", ["expires_at"], unique=False)
    op.create_index(op.f("ix_admin_magic_links_user_id"), "admin_magic_links", ["user_id"], unique=False)
    op.create_table(
        "admin_sessions",
        sa.Column("session_id", sa.String(length=64), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.Column("user_agent", sa.String(length=512), nullable=True),
        sa.Column("ip", sa.String(length=64), nullable=True),
        sa.PrimaryKeyConstraint("session_id"),
    )
    op.create_index(op.f("ix_admin_sessions_expires_at"), "admin_sessions", ["expires_at"], unique=False)
    op.create_index(op.f("ix_admin_sessions_user_id"), "admin_sessions", ["user_id"], unique=False)
    op.create_table(
        "admins",
        sa.Column("id", sa.BigInteger(), autoincrement=False, nullable=False),
        sa.Column("state", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "chat_links",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("text", sa.String(), nullable=False),
        sa.Column("link", sa.String(), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("link"),
        sa.UniqueConstraint("text"),
    )
    op.create_table(
        "chat_member_snapshots",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("chat_id", sa.BigInteger(), nullable=False),
        sa.Column("member_count", sa.Integer(), nullable=False),
        sa.Column("captured_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_chat_member_snapshots_captured_at"), "chat_member_snapshots", ["captured_at"], unique=False
    )
    op.create_index(
        "ix_chat_member_snapshots_chat_id_captured_at",
        "chat_member_snapshots",
        ["chat_id", "captured_at"],
        unique=False,
    )
    op.create_table(
        "chats",
        sa.Column("id", sa.BigInteger(), autoincrement=False, nullable=False),
        sa.Column("title", sa.String(), nullable=True),
        sa.Column("resource_status", sa.String(), nullable=False),
        sa.Column("is_forum", sa.Boolean(), nullable=False),
        sa.Column("welcome_message", sa.String(), nullable=True),
        sa.Column("time_delete", sa.Integer(), nullable=False),
        sa.Column("is_welcome_enabled", sa.Boolean(), nullable=False),
        sa.Column("is_captcha_enabled", sa.Boolean(), nullable=False),
        sa.Column("parent_chat_id", sa.BigInteger(), nullable=True),
        sa.Column("relation_notes", sa.String(), nullable=True),
        sa.Column("photo_file_id", sa.String(), nullable=True),
        sa.Column("last_synced_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("modified_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["parent_chat_id"], ["chats.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_chats_parent_chat_id"), "chats", ["parent_chat_id"], unique=False)
    op.create_table(
        "join_checks",
        sa.Column("query_id", sa.String(length=128), nullable=False),
        sa.Column("chat_id", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("passed_at", sa.DateTime(), nullable=True),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("query_id"),
    )
    op.create_index(op.f("ix_join_checks_chat_id"), "join_checks", ["chat_id"], unique=False)
    op.create_index(op.f("ix_join_checks_expires_at"), "join_checks", ["expires_at"], unique=False)
    op.create_index(op.f("ix_join_checks_user_id"), "join_checks", ["user_id"], unique=False)
    op.create_table(
        "messages",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("chat_id", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("message_id", sa.BigInteger(), nullable=False),
        sa.Column("message", sa.String(), nullable=True),
        sa.Column("message_info", sa.JSON(), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.Column("spam", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_messages_chat_id"), "messages", ["chat_id"], unique=False)
    op.create_index(op.f("ix_messages_user_id"), "messages", ["user_id"], unique=False)
    op.create_table(
        "pending_actions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("origin", sa.String(length=16), nullable=False),
        sa.Column("initiator_id", sa.BigInteger(), nullable=False),
        sa.Column("action", sa.String(length=32), nullable=False),
        sa.Column("chat_id", sa.BigInteger(), nullable=True),
        sa.Column("target_user_id", sa.BigInteger(), nullable=False),
        sa.Column("params", sa.JSON(), nullable=False),
        sa.Column("reason", sa.String(), nullable=True),
        sa.Column("admin_chat_id", sa.BigInteger(), nullable=True),
        sa.Column("admin_message_id", sa.BigInteger(), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("resolved_by", sa.BigInteger(), nullable=True),
        sa.Column("resolved_at", sa.DateTime(), nullable=True),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint("action IN ('ban', 'blacklist')", name="ck_pending_actions_action"),
        sa.CheckConstraint("origin IN ('mcp')", name="ck_pending_actions_origin"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_pending_actions_chat_id"), "pending_actions", ["chat_id"], unique=False)
    op.create_index(op.f("ix_pending_actions_initiator_id"), "pending_actions", ["initiator_id"], unique=False)
    op.create_index("ix_pending_actions_status_expires_at", "pending_actions", ["status", "expires_at"], unique=False)
    op.create_index(op.f("ix_pending_actions_target_user_id"), "pending_actions", ["target_user_id"], unique=False)
    op.create_table(
        "spam_pings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("chat_id", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("message_id", sa.BigInteger(), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("matches", sa.JSON(), nullable=False),
        sa.Column("snippet", sa.String(), nullable=True),
        sa.Column("detected_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_spam_pings_chat_id"), "spam_pings", ["chat_id"], unique=False)
    op.create_index("ix_spam_pings_chat_id_detected_at", "spam_pings", ["chat_id", "detected_at"], unique=False)
    op.create_index("ix_spam_pings_detected_at", "spam_pings", ["detected_at"], unique=False)
    op.create_table(
        "users",
        sa.Column("id", sa.BigInteger(), autoincrement=False, nullable=False),
        sa.Column("username", sa.String(), nullable=True),
        sa.Column("first_name", sa.String(), nullable=True),
        sa.Column("last_name", sa.String(), nullable=True),
        sa.Column("verify", sa.Boolean(), nullable=False),
        sa.Column("blocked", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("modified_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("users")
    op.drop_index("ix_spam_pings_detected_at", table_name="spam_pings")
    op.drop_index("ix_spam_pings_chat_id_detected_at", table_name="spam_pings")
    op.drop_index(op.f("ix_spam_pings_chat_id"), table_name="spam_pings")
    op.drop_table("spam_pings")
    op.drop_index(op.f("ix_pending_actions_target_user_id"), table_name="pending_actions")
    op.drop_index("ix_pending_actions_status_expires_at", table_name="pending_actions")
    op.drop_index(op.f("ix_pending_actions_initiator_id"), table_name="pending_actions")
    op.drop_index(op.f("ix_pending_actions_chat_id"), table_name="pending_actions")
    op.drop_table("pending_actions")
    op.drop_index(op.f("ix_messages_user_id"), table_name="messages")
    op.drop_index(op.f("ix_messages_chat_id"), table_name="messages")
    op.drop_table("messages")
    op.drop_index(op.f("ix_join_checks_user_id"), table_name="join_checks")
    op.drop_index(op.f("ix_join_checks_expires_at"), table_name="join_checks")
    op.drop_index(op.f("ix_join_checks_chat_id"), table_name="join_checks")
    op.drop_table("join_checks")
    op.drop_index(op.f("ix_chats_parent_chat_id"), table_name="chats")
    op.drop_table("chats")
    op.drop_index("ix_chat_member_snapshots_chat_id_captured_at", table_name="chat_member_snapshots")
    op.drop_index(op.f("ix_chat_member_snapshots_captured_at"), table_name="chat_member_snapshots")
    op.drop_table("chat_member_snapshots")
    op.drop_table("chat_links")
    op.drop_table("admins")
    op.drop_index(op.f("ix_admin_sessions_user_id"), table_name="admin_sessions")
    op.drop_index(op.f("ix_admin_sessions_expires_at"), table_name="admin_sessions")
    op.drop_table("admin_sessions")
    op.drop_index(op.f("ix_admin_magic_links_user_id"), table_name="admin_magic_links")
    op.drop_index(op.f("ix_admin_magic_links_expires_at"), table_name="admin_magic_links")
    op.drop_table("admin_magic_links")
    # ### end Alembic commands ###
