"""Backward-compatibility shim — re-exports from app.agent.channel.review.agent."""

from app.agent.channel.review.agent import (  # noqa: F401
    _AGENT_TIMEOUT_SECONDS,
    _EDIT_KEYWORDS,
    _FOOTER_PLACEHOLDER,
    _MAX_HISTORY,
    _MAX_REVIEW_CONVERSATIONS,
    _REVIEW_CONVERSATION_TTL,
    _SYSTEM_PROMPT_TEMPLATE,
    ReviewAgentDeps,
    _evict_review_conversations,
    _get_post_lock,
    _has_tool_call,
    _looks_like_edit_request,
    _message_to_post,
    _post_locks,
    _review_agent_turn_inner,
    _review_conversations,
    _review_last_access,
    clear_review_conversation,
    create_review_agent,
    register_message,
    resolve_post_id,
    review_agent_turn,
)

__all__ = [
    "ReviewAgentDeps",
    "_AGENT_TIMEOUT_SECONDS",
    "_EDIT_KEYWORDS",
    "_FOOTER_PLACEHOLDER",
    "_MAX_HISTORY",
    "_MAX_REVIEW_CONVERSATIONS",
    "_REVIEW_CONVERSATION_TTL",
    "_SYSTEM_PROMPT_TEMPLATE",
    "_evict_review_conversations",
    "_get_post_lock",
    "_has_tool_call",
    "_looks_like_edit_request",
    "_message_to_post",
    "_post_locks",
    "_review_agent_turn_inner",
    "_review_conversations",
    "_review_last_access",
    "clear_review_conversation",
    "create_review_agent",
    "register_message",
    "resolve_post_id",
    "review_agent_turn",
]
