"""Application configuration using Pydantic settings."""

from __future__ import annotations

from typing import TYPE_CHECKING, Any, Literal

from pydantic import Field, field_validator
from pydantic_settings import BaseSettings, SettingsConfigDict

if TYPE_CHECKING:
    from app.channel.config import ChannelAgentSettings


class DatabaseSettings(BaseSettings):
    """Database configuration."""

    user: str = Field(..., description="Database user")
    password: str = Field(..., description="Database password")
    host: str = Field(default="db", description="Database host")
    port: int = Field(default=5432, description="Database port")
    name: str = Field(..., description="Database name")

    model_config = SettingsConfigDict(
        env_prefix="DB_",
        case_sensitive=False,
        env_file=".env",
        env_file_encoding="utf-8",
        extra="ignore",
    )

    @property
    def url(self) -> str:
        """Get async database URL."""
        from sqlalchemy.engine import URL

        return URL.create(
            "postgresql+asyncpg",
            username=self.user,
            password=self.password,
            host=self.host,
            port=self.port,
            database=self.name,
        ).render_as_string(hide_password=False)

    @property
    def sync_url(self) -> str:
        """Get sync database URL for Alembic."""
        from sqlalchemy.engine import URL

        return URL.create(
            "postgresql",
            username=self.user,
            password=self.password,
            host=self.host,
            port=self.port,
            database=self.name,
        ).render_as_string(hide_password=False)


class TelegramSettings(BaseSettings):
    """Moderator bot configuration."""

    token: str = Field(..., description="Moderator bot token from BotFather")

    model_config = SettingsConfigDict(
        env_prefix="MODERATOR_BOT_",
        case_sensitive=False,
        env_file=".env",
        env_file_encoding="utf-8",
        extra="ignore",
    )


class AdminSettings(BaseSettings):
    """Admin configuration."""

    super_admins: list[int] = Field(..., description="List of super admin user IDs")
    report_chat_id: int | None = Field(default=None, description="Chat ID for reports")

    model_config = SettingsConfigDict(
        env_prefix="ADMIN_",
        case_sensitive=False,
        env_file=".env",
        env_file_encoding="utf-8",
        extra="ignore",
    )

    @field_validator("super_admins", mode="before")
    @classmethod
    def parse_admin_list(cls, v: Any) -> list[int]:
        """Parse comma-separated admin IDs."""
        if isinstance(v, str):
            return [int(admin_id.strip()) for admin_id in v.split(",") if admin_id.strip()]
        if isinstance(v, list):
            return [int(admin_id) for admin_id in v]
        if isinstance(v, int):
            return [v]
        raise ValueError("super_admins must be a comma-separated string, list, or integer")

    @property
    def default_report_chat_id(self) -> int:
        """Get default report chat ID (first super admin)."""
        return self.report_chat_id or self.super_admins[0]


class WebApiSettings(BaseSettings):
    """Admin web UI / HTTP API configuration."""

    auth_mode: Literal["telegram", "magic_link"] = Field(
        default="telegram",
        description="Admin auth mode: telegram login or bot-issued magic links.",
    )
    public_url: str = Field(
        default="",
        description="Public web UI URL used when generating magic links from Telegram.",
    )
    magic_link_ttl_minutes: int = Field(
        default=15,
        description="TTL for one-time magic links generated by the main admin Telegram command.",
    )
    session_ttl_days: int = Field(default=30, description="Admin session TTL in days")
    session_cookie_name: str = Field(default="konnekt_admin_session")
    session_cookie_secure: bool = Field(
        default=True,
        description="Set Secure flag on session cookie. Disable only for local http:// dev.",
    )
    session_cookie_samesite: str = Field(default="lax", description="SameSite: lax|strict|none")

    model_config = SettingsConfigDict(
        env_prefix="WEBAPI_",
        case_sensitive=False,
        env_file=".env",
        env_file_encoding="utf-8",
        extra="ignore",
    )

    @field_validator("magic_link_ttl_minutes")
    @classmethod
    def validate_magic_link_ttl(cls, v: int) -> int:
        if v <= 0:
            raise ValueError("magic_link_ttl_minutes must be positive")
        return v

    @property
    def allowed_origins(self) -> list[str]:
        """Origins the API accepts, derived from where the UI is served.

        This used to be its own setting, documented as comma-separated — and it
        could never work that way: pydantic-settings JSON-decodes a list field
        at the source, before the validator that split on commas could run, so
        any real value raised at startup. Production therefore left it empty and
        fell back to the local development origin, which went unnoticed only
        because the UI and the API share a host and never trigger CORS.

        One origin, derived from the URL already configured, cannot disagree
        with itself. The trailing slash goes because browsers compare exactly.
        """
        return [self.public_url.rstrip("/")] if self.public_url else []


class LoggingSettings(BaseSettings):
    """Logging configuration."""

    level: str = Field(default="INFO", description="Log level")
    format: str = Field(default="%(asctime)s - %(name)s - %(levelname)s - %(message)s", description="Log format")
    file_path: str | None = Field(default="logs/bot.log", description="Log file path")
    max_bytes: int = Field(default=10485760, description="Max log file size in bytes (10MB)")
    backup_count: int = Field(default=5, description="Number of backup log files")

    model_config = SettingsConfigDict(
        env_prefix="LOG_",
        case_sensitive=False,
        env_file=".env",
        env_file_encoding="utf-8",
        extra="ignore",
    )


class OpenRouterSettings(BaseSettings):
    """Shared LLM credentials used by all agents."""

    api_key: str = Field(default="", description="OpenRouter API key")
    base_url: str = Field(default="https://openrouter.ai/api/v1", description="OpenRouter API base URL")

    model_config = SettingsConfigDict(
        env_prefix="OPENROUTER_",
        case_sensitive=False,
        env_file=".env",
        env_file_encoding="utf-8",
        extra="ignore",
    )


class BraveSettings(BaseSettings):
    """Brave Search API configuration."""

    api_key: str = Field(default="", description="Brave Search API key for web search")

    model_config = SettingsConfigDict(
        env_prefix="BRAVE_",
        case_sensitive=False,
        env_file=".env",
        env_file_encoding="utf-8",
        extra="ignore",
    )


class ModerationSettings(BaseSettings):
    """Heuristic moderation configuration.

    What remains after the LLM agent: the ad detector, which matches t.me links
    and @handles and records what it finds. No model, no escalation timeout —
    both belonged to a decision step that a person now makes.
    """

    ad_detector_enabled: bool = Field(
        default=True,
        description="Whether the heuristic ad detector (t.me / @username) records spam_pings",
    )
    ad_detector_whitelist: list[str] = Field(
        default_factory=list,
        description="Handles never flagged by the ad detector (e.g. ['@konnekt_channel', '@work_azamat'])",
    )
    ad_detector_snippet_chars: int = Field(
        default=200,
        description="Max chars of message text stored alongside each spam_ping",
    )

    model_config = SettingsConfigDict(
        env_prefix="MODERATION_",
        case_sensitive=False,
        env_file=".env",
        env_file_encoding="utf-8",
        extra="ignore",
    )


class TelethonSettings(BaseSettings):
    """Telethon (Telegram Client API) configuration for userbot features."""

    api_id: int = Field(default=0, description="API ID from https://my.telegram.org")
    api_hash: str = Field(default="", description="API hash from https://my.telegram.org")
    phone: str | None = Field(default=None, description="Phone number for initial auth")

    # Not configurable: docker-compose mounts the session file by this exact
    # name. A setting that could disagree with the mount would make Telethon
    # start an unauthorised session instead of failing.
    session_name: str = "moderator_userbot"

    model_config = SettingsConfigDict(
        env_prefix="TELETHON_",
        case_sensitive=False,
        env_file=".env",
        env_file_encoding="utf-8",
        extra="ignore",
    )

    @property
    def active(self) -> bool:
        """True when there are credentials to connect with.

        There is no separate enable flag: without both halves the client cannot
        work, and with them there is nothing to gain by pretending otherwise.
        """
        return bool(self.api_id and self.api_hash)


class SponsoredAdsSettings(BaseSettings):
    """Sponsored ads rate-card funnel configuration."""

    moderator_chat_id: int = Field(
        default=0,
        description="Chat that receives ad-review alerts; unset disables the funnel",
    )
    sales_contact: str = Field(
        default="",
        description="@username shown in the rate card for ad-sales questions",
    )

    @property
    def active(self) -> bool:
        """True when there is somewhere to send an alert."""
        return bool(self.moderator_chat_id)

    model_config = SettingsConfigDict(
        env_prefix="SPONSORED_ADS_",
        case_sensitive=False,
        env_file=".env",
        env_file_encoding="utf-8",
        extra="ignore",
    )


class McpSettings(BaseSettings):
    """MCP server served by the bot process for external agent clients.

    The MCP endpoint is a second admin control plane alongside the cookie-authed
    web UI. The token is a shared secret presented as ``Authorization: Bearer``;
    it is not a user session, and it is also the switch — no token, no endpoint.

    It runs in the bot process rather than the web API because moderation tools
    need what only that process holds: the Telethon user session, whose SQLite
    file a second process cannot open, and the bot whose dispatcher answers the
    confirmation buttons it sends.
    """

    token: str = Field(default="", description="Bearer token required by MCP clients; unset disables the endpoint")
    initiator_id: int = Field(
        default=0,
        description=(
            "Telegram ID of the admin this token acts as. A ban is an attributable act, "
            "and the token names a runtime rather than a person, so the attribution has "
            "to be configured. Destructive tools stay closed while this is unset."
        ),
    )
    max_drafts_per_hour: int = Field(
        default=10,
        description="Cap on generate_and_send_for_review calls per hour (0 disables the cap)",
    )

    # Not configurable. The compose port mapping hard-codes the container side,
    # so a configurable port would bind the app to one number while the mapping
    # forwarded another. The path is fixed for the same reason a URL is.
    path: str = "/api/mcp"
    host: str = "0.0.0.0"  # noqa: S104 — inside the container; the mapping is loopback-only
    port: int = 8788

    @property
    def active(self) -> bool:
        """True when there is a token to authenticate with.

        Failing closed keeps a misconfigured deploy from exposing admin tooling
        without authentication — and with no separate flag there is nothing that
        can claim to be enabled while the door has no lock.
        """
        return bool(self.token)

    model_config = SettingsConfigDict(
        env_prefix="MCP_",
        case_sensitive=False,
        env_file=".env",
        env_file_encoding="utf-8",
        extra="ignore",
    )


class AppSettings(BaseSettings):
    """Main application settings."""

    debug: bool = Field(default=False, description="Debug mode")
    environment: str = Field(default="development", description="Environment name")
    timezone: str = Field(default="UTC", description="Application timezone")

    database: DatabaseSettings = Field(default_factory=DatabaseSettings)
    telegram: TelegramSettings = Field(default_factory=TelegramSettings)
    admin: AdminSettings = Field(default_factory=AdminSettings)
    logging: LoggingSettings = Field(default_factory=LoggingSettings)
    openrouter: OpenRouterSettings = Field(default_factory=OpenRouterSettings)
    brave: BraveSettings = Field(default_factory=BraveSettings)
    moderation: ModerationSettings = Field(default_factory=ModerationSettings)
    telethon: TelethonSettings = Field(default_factory=TelethonSettings)
    webapi: WebApiSettings = Field(default_factory=WebApiSettings)
    sponsored_ads: SponsoredAdsSettings = Field(default_factory=SponsoredAdsSettings)
    mcp: McpSettings = Field(default_factory=McpSettings)

    @property
    def channel(self) -> ChannelAgentSettings:
        """Lazily load and cache ChannelAgentSettings singleton."""
        if not hasattr(self, "_channel_settings"):
            from app.channel.config import ChannelAgentSettings

            object.__setattr__(self, "_channel_settings", ChannelAgentSettings())
        return self._channel_settings  # ty: ignore[unresolved-attribute]

    model_config = SettingsConfigDict(
        env_prefix="APP_",
        env_file=".env",
        env_file_encoding="utf-8",
        case_sensitive=False,
        extra="ignore",
    )


# Global settings instance
settings = AppSettings()
